schema_version = "1.0.0"
id = "overscan"
version = "1.2.3"
name = "Overscan Render"
tagline = "Render with an overscan"
maintainer = "Blender Bob/Robert Rioux"
type = "add-on"
website = "https://github.com/riouxr/Overscan"
tags = ["Camera"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]